[package]
name = "regularly_fetch_text"
version = "0.1.0"
edition = "2021"

[dependencies]
article_scraper = "2.1.0"
futures = "0.3.30"
indicatif = "0.17.8"
mongodb = "3.0.1"
reqwest = "0.12.5"
scraper = "0.19.0"
tokio = {version = "1.38.0", features = ["full"]}
url = "2.5.2"
